openapi: 3.0.0
info:
  title: Steam library API
  version: 1.0.0
  description: An API for managing a Steam games library
servers:
  - url: 'https://smashblu.github.io/steam-games/'
paths:
  /games:
    get:
      tags:
        - games
      summary: List games
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Game'
                title: GameListOk
          description: A JSON array containing game objects.
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerErrror'
      parameters:
        - $ref: '#/components/parameters/title'
        - $ref: '#/components/parameters/rating'
        - $ref: '#/components/parameters/releaseDate'
        - $ref: '#/components/parameters/currentPrice'
        - $ref: '#/components/parameters/publisherId'
      description: Fetches a comprehensive list of all games available in the library. Each game object includes essential details such as the game's name, ESRB rating, release date, current price, and publisher.
      operationId: ListGames
    post:
      tags:
        - games
      summary: Create game
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
          description: 'The request was successful, and a new resource was created. The URI of the newly created resource can be found in the response''s Location header.'
        '400':
          $ref: '#/components/responses/BadRequest'
      description: Creates a new game entry in the library. The request must include the game's name.
      operationId: createGame
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Game'
        required: true
        description: Details of the game to be created.
  /games/{gameId}:
    get:
      tags:
        - games
      summary: Get game
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
          description: A JSON object containing the game details.
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerErrror'
      parameters:
        - $ref: '#/components/parameters/gameId'
        - $ref: '#/components/parameters/publisherId'
      description: Fetches details of a specific game by its unique identifier. The response includes the game's name, ESRB rating, release date, current price, and publisher.
      operationId: getGame
    patch:
      tags:
        - games
      summary: Update game
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
          description: 'The request was successful, and a new resource was created. The URI of the newly created resource can be found in the response''s Location header.'
        '400':
          $ref: '#/components/responses/BadRequest'
    delete:
      tags:
        - games
      summary: Delete game
      responses:
        '204':
          content:
            application/json:
              schema:
                type: string
                title: DeleteGameNoContent
          description: The request was successful, but there is no content to return in the response.
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerErrror'
      description: Deletes a specific game from the library using its unique identifier.
        The operation confirms successful deletion.
      operationId: deleteGame
components:
  schemas:
    Game:
      type: object
      required:
        - gameId
        - title
      properties:
        gameId:
          type: integer
        title:
          type: string
        rating:
          type: string
        releaseDate:
          type: string
        currentPrice:
          type: integer
        publisher:
          $ref: '#/components/schemas/Publisher'
    Publisher:
      type: object
      required:
        - publisherId
        - name
      properties:
        publisherId:
          type: integer
        name:
          type: string
      description: Creator of games.
  responses:
    Conflict:
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
      description: The request could not be completed due to a conflict with the current state of the resource. Resolve the conflict and try again.
    NotFound:
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
      description: The server cannot find the requested resource. The endpoint may be invalid or the resource may no longer exist.
    BadRequest:
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
      description: The server could not understand the request due to invalid syntax. The client should modify the request and try again.
    InternalServerErrror:
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
      description: The server encountered an unexpected condition that prevented it from fulfilling the request. Report the issue to the support team if it persists.
  parameters:
    title:
      in: query
      name: title
      style: form
      schema:
        type: string
      required: false
      description: Filter the list of games according to the title.
    rating:
      in: query
      name: rating
      schema:
        type: string
      required: false
      description: Filter the list of games according to rating.
    releaseDate:
      in: query
      name: releaseDate
      schema:
        type: string
      required: false
      description: Filter the list of games according to release date.
    currentPrice:
      in: query
      name: currentPrice
      schema:
        type: integer
      required: false
      description: Filter the list of games according to price.
    publisherId:
      name: publisherId
      in: query
      description: Filter the list of games accodring to the publisher.
      schema:
        type: integer
    gameId:
      name: gameId
      required: true
      in: path
      description: Path parameter to retrieve games by.
      schema:
        type: integer
tags:
  - name: games
    description: Endpoints dealing with game entities.
