openapi: 3.0.0
info:
  title: Steam Library API
  version: "0.1"
  license:
    name: MIT
servers:
  - url: <URL>
paths:
  /games:
    get:
      summary: List all games in library
      operationId: listGames
      tags:
      - games
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            maximum: 100
            format: int32
      responses:
        '200':
          description: A paged array of games
          content:
            application/json:
              schema:
                $ref: '/components/schemas/Games'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Add a game to library
      operationId: addGame
      tags:
      - games
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Library'
        required: true
      responses:
        '201':
          description: Null response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Games'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /games/{gameId}:
    get:
      summary: List game by ID
      operationId: showGameById
      tags:
      - games
      parameters:
        - name: gameId
          in: path
          required: true
          description: The ID of the game to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Library'
        default: 
          description: unexptected error
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
    put:
      summary: Update game by ID
      operationId: updateGameById
      tags:
      - games
      parameters:
        - name: gameId
          in: path
          required: true
          description: The ID of the game to update
      responses:
        '201':
          description: Null response
          content:
            application/json:
              schema:
                $ref: '/components/schemas/Library'
        '204':
          description: No content
        default: 
          description: unexptected error
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
components:
  schemas:
    Library:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
        username:
          type: string
        required:
          - libraryId
          - username
    Games:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
        title:
          type: string
        release_date:
          type: string
        rating:
          type: array
          items:
          - "E"
          - "E10+"
          - "T"
          - "M"
          - "AO"
          - "RP"
        current_price:
          type: number
    Publisher:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
        name:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
